### ISSUE TITLE
Fix request args validation

### ISSUE THREAD

**Issue by nightfox0909** [shriniket03/EasyBoard#1]
Currently the request validation for the api endpoints do not validate the presence of arguments and need explicit typecasting. 
Example :
`if 'originLat' and 'originLong' and 'destinLat' and 'destinLong' in request.args:`

Its suggested to change this to the approach mentioned in https://stackoverflow.com/a/30943884 and check for None in the required arguments. 
The above line would therefore change to 
```python
origin = ( request.args.get('originLat', None, type=float)), request.args.get('originLat', None, type=float)) )
destin = ( request.args.get('destinLat', None, type=float)), request.args.get('destinLat', None, type=float)) )
if None in origin or None in destin:
    return "Error: Parameters not properly provided. Please specify properly."
```

The above approach written as is, please test locally before pushing codebase to prod. Good first pass candidate for unittests.

**Comment by shriniket03** [comment]
fixed
