### ISSUE TITLE
Fix endpoint latency

### ISSUE THREAD

**Issue by nightfox0909** [shriniket03/EasyBoard#3]
Current endpoint latency in seconds is as below
```
http://127.0.0.1:5000/api/distance took 0.005982398986816406
http://127.0.0.1:5000/api/routing took 0.05385708808898926
http://127.0.0.1:5000/api/busStop took 276.43966484069824
http://127.0.0.1:5000/api/busCode took 0.25815439224243164
```

Looks like fixing busStop and busCode latency should fix most of the unresponsiveness. 

Specifically, the section where google search is used contributes to the bulk of the time. This blocks the WSGI server as well. Suggestion is to change this part into a static graph updated everyday offline. Further deep dive into this method is warranted!

Test params
```
params = {
'originLat' : 1.3358620948905815,
'originLong' : 103.7471113133555,
'destinLat' : 1.3129619921562072,
'destinLong' : 103.7601730272527,
'currentBusStop' : 28019, #Aft Toh Tuck Ave
'busNumber' : 188,
'destinBusStop' : 20019, #'Blk 431'
'numStops' : 7,
'originBusStop' : 28651,# 'Opp IMM Bldg'
}
```
Test code
```python
import time
import requests

api_ends = [
    'http://127.0.0.1:5000/api/distance',
    'http://127.0.0.1:5000/api/routing',
    'http://127.0.0.1:5000/api/busStop',
    'http://127.0.0.1:5000/api/busCode'
]

params = {
'originLat' : 1.3358620948905815,
'originLong' : 103.7471113133555,
'destinLat' : 1.3129619921562072,
'destinLong' : 103.7601730272527,
'currentBusStop' : 28019, #Aft Toh Tuck Ave
'busNumber' : 188,
'destinBusStop' : 20019, #'Blk 431'
'numStops' : 7,
'originBusStop' : 28651,# 'Opp IMM Bldg'
}

for api in api_ends:
    st = time.time()
    requests.get(api, params=params)
    end = time.time()
    print(f'{api} took {end-st}')

```

**Comment by shriniket03** [comment]
https://easyboardactual.et.r.appspot.com/api/distance took 0.24899959564208984
https://easyboardactual.et.r.appspot.com/api/routing took 0.5200943946838379
https://easyboardactual.et.r.appspot.com/api/busStop took 0.19499969482421875
https://easyboardactual.et.r.appspot.com/api/busCode took 0.4109988212585449

--> new outputs (might be larger due to remote usage of API
